import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Palette, range, scale, opacity and vertical exaggeration as persistent
// renderer state (IMAP s7-display-controls). No change here reprocesses data.
import { Anchor, Button, Fieldset, Group, NumberInput, SegmentedControl, Select, Slider, Stack, Text, Title, Tooltip } from "@mantine/core";
import { cssGradient, logScaleProblem, PALETTES } from "../renderer/colour";
const EXAGGERATION = [1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000];
export function DisplayPanel({ display, fullSubsetRange, enabled, onChange, onUseFullSubsetRange, onResetCamera }) {
    const logProblem = logScaleProblem(display.range.minimum, display.range.maximum);
    const stepIndex = EXAGGERATION.reduce((best, v, i) => Math.abs(v - display.verticalExaggeration) < Math.abs(EXAGGERATION[best] - display.verticalExaggeration) ? i : best, 0);
    const setRange = (key) => (value) => {
        if (typeof value === "number" && Number.isFinite(value))
            onChange({ range: { ...display.range, [key]: value } });
    };
    return (_jsxs(Stack, { gap: "sm", component: "section", "aria-label": "Display", children: [_jsx(Title, { order: 2, size: "h6", tt: "uppercase", c: "dimmed", children: "Display" }), _jsx(Fieldset, { variant: "unstyled", disabled: !enabled, children: _jsxs(Stack, { gap: "sm", children: [_jsx(Select, { label: "Palette", value: display.palette, allowDeselect: false, data: PALETTES.map((p) => ({ value: p, label: p })), onChange: (v) => v && onChange({ palette: v }), leftSection: _jsx("div", { className: "colour-bar", style: { width: 16, background: cssGradient(display.palette) } }) }), _jsxs(Group, { grow: true, gap: "xs", children: [_jsx(NumberInput, { label: "Range min", value: display.range.minimum, decimalScale: 3, onChange: setRange("minimum") }), _jsx(NumberInput, { label: "Range max", value: display.range.maximum, decimalScale: 3, onChange: setRange("maximum") })] }), _jsxs(Text, { size: "xs", c: "dimmed", children: [display.rangeSource === "full-subset" ? "Range of the full selected subset, before sampling." : "Custom range.", " ", display.rangeSource === "custom" && fullSubsetRange?.minimum != null && (_jsx(Anchor, { component: "button", size: "xs", onClick: onUseFullSubsetRange, children: "Use full-subset range" }))] }), _jsx(Tooltip, { label: logProblem ?? "", disabled: !logProblem, position: "right", children: _jsx(SegmentedControl, { fullWidth: true, value: display.scale, "aria-label": "Colour scale", onChange: (v) => onChange({ scale: v }), data: [{ value: "linear", label: "Linear" }, { value: "log", label: "Logarithmic", disabled: logProblem !== null }] }) }), _jsxs("div", { children: [_jsxs(Text, { size: "sm", fw: 500, children: ["Opacity ", _jsxs(Text, { span: true, c: "dimmed", size: "sm", children: [Math.round(display.opacity * 100), "%"] })] }), _jsx(Slider, { "aria-label": "Opacity", min: 0.05, max: 1, step: 0.05, value: display.opacity, onChange: (opacity) => onChange({ opacity }), label: (v) => `${Math.round(v * 100)}%` })] }), _jsxs("div", { children: [_jsxs(Text, { size: "sm", fw: 500, children: ["Vertical exaggeration ", _jsxs(Text, { span: true, c: "dimmed", size: "sm", children: ["\u00D7", display.verticalExaggeration] })] }), _jsx(Slider, { "aria-label": "Vertical exaggeration", min: 0, max: EXAGGERATION.length - 1, step: 1, value: stepIndex, label: (i) => `×${EXAGGERATION[i]}`, onChange: (i) => onChange({ verticalExaggeration: EXAGGERATION[i] }) })] }), _jsx(Button, { variant: "light", onClick: onResetCamera, children: "Fly to region" })] }) })] }));
}
